String myFirstName = 'Travis';
String myLastName = 'Dykstra';
Integer myAge = 37;

System.debug('What is the valude of myFirstName ' + myFirstName);
System.debug('What is the valude of myLastName ' + myLastName);
System.debug('What is my age ' + myAge);

List<String> colors = new List<string>;
colors.add('Blue')

// Ternary

Boolean result = (colors[0] == red ? true:false);

// Null Coalescing Operator